services:
  - type: web
    name: finsentiment-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 2 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.18
      - key: INDIAN_STOCK_API_KEY
        sync: false
      - key: INDIAN_STOCK_API_KEY_2
        sync: false
      - key: INDIAN_STOCK_API_KEY_3
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_KEY
        sync: false
      - key: DEMO_MODE
        value: false
    healthCheckPath: /api/health
    autoDeploy: true
    region: oregon
    plan: free
